(function(){
var root=document.documentElement,path=location.pathname.split("/").pop()||"index";if(path.indexOf(".html")<0)path+=".html";if(path==="groups.html")path="cohorts.html";
var logo='<svg viewBox="0 0 266 54" role="img" aria-label="Hackcessible"><text x="0" y="39" font-family="Jakarta,Arial" font-size="35" font-weight="800" letter-spacing="-2">Hack</text><path d="M82 37V24c0-12 10-20 22-20s22 8 22 20v13" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round"/><circle cx="82" cy="39" r="4" fill="currentColor"/><circle cx="126" cy="39" r="4" fill="currentColor"/><text x="132" y="39" font-family="Jakarta,Arial" font-size="35" font-weight="800" letter-spacing="-2">cessible</text></svg>';
var nav=[["index.html","Home"],["cohorts.html","Cohorts"],["people.html","People"],["contact.html","Contact"]],links=nav.map(function(n){return '<a class="nav-link" href="'+n[0]+'"'+(n[0]===path?' aria-current="page"':'')+'>'+n[1]+'</a>'}).join("");
var mount=document.getElementById("site-nav");if(mount)mount.innerHTML='<a class="skip" href="#main">Skip to content</a><div class="nav-shell"><nav class="nav" aria-label="Primary"><a class="brand" href="index.html">'+logo+'</a><div class="nav-links" id="navLinks">'+links+'</div><div class="nav-actions"><button class="theme-toggle" type="button" aria-label="Toggle dark mode" aria-pressed="false"><svg class="icon-sun" viewBox="0 0 24 24"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4 12H2m20 0h-2M5 5l2 2m10 10 2 2m0-14-2 2M7 17l-2 2"/></svg><svg class="icon-moon" viewBox="0 0 24 24"><path d="M21 14a9 9 0 1 1-11-11 7 7 0 0 0 11 11z"/></svg></button><button class="menu-toggle" type="button" aria-label="Open menu" aria-expanded="false"><svg viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16"/></svg></button></div></nav></div><div class="nav-spacer"></div>';
var foot=document.getElementById("site-footer");if(foot)foot.innerHTML='<footer class="foot-wrap"><div class="wrap foot"><div><h2>Hackcessible</h2><small>Student-led assistive technology exploration in Nairobi.</small></div><div><strong>Explore</strong><a href="cohorts.html">Cohorts</a><a href="people.html">People</a><a href="contact.html">Contact</a></div><div><strong>Contact</strong><a href="mailto:nbi.cime@aku.edu">nbi.cime@aku.edu</a><small>CIME · Aga Khan University<br>Nairobi, Kenya</small></div></div></footer>';
var theme=document.querySelector(".theme-toggle");if(theme){theme.setAttribute("aria-pressed",String(root.dataset.theme==="dark"));theme.onclick=function(){var dark=root.dataset.theme!=="dark";if(dark)root.dataset.theme="dark";else delete root.dataset.theme;theme.setAttribute("aria-pressed",String(dark));try{localStorage.setItem("hk-theme",dark?"dark":"light")}catch(e){}}}
var menu=document.querySelector(".menu-toggle"),menuLinks=document.getElementById("navLinks");if(menu){menu.onclick=function(){var open=menuLinks.classList.toggle("open");menu.setAttribute("aria-expanded",String(open));menu.setAttribute("aria-label",open?"Close menu":"Open menu")};menuLinks.onclick=function(e){if(e.target.closest("a")){menuLinks.classList.remove("open");menu.setAttribute("aria-expanded","false")}}}
var reduce=matchMedia("(prefers-reduced-motion: reduce)").matches,intro=document.getElementById("intro");if(intro){var seen=false;try{seen=sessionStorage.getItem("hk-intro")}catch(e){}if(reduce||seen)intro.remove();else{try{sessionStorage.setItem("hk-intro","1")}catch(e){}setTimeout(function(){intro.classList.add("done");setTimeout(function(){intro.remove()},650)},3000)}}
var observer=new IntersectionObserver(function(entries){entries.forEach(function(e,i){if(e.isIntersecting){setTimeout(function(){e.target.classList.add("in")},Math.min(i*70,280));observer.unobserve(e.target)}})},{threshold:.12});document.querySelectorAll(".reveal").forEach(function(el){observer.observe(el)});
var wipe=document.createElement("div");wipe.className="page-wipe";document.body.appendChild(wipe);document.addEventListener("click",function(e){var a=e.target.closest("a");if(!a||e.defaultPrevented||e.button||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey||a.target||a.hasAttribute("download")||a.protocol==="mailto:"||a.origin!==location.origin)return;if(a.pathname===location.pathname&&a.hash)return;e.preventDefault();if(reduce){location.href=a.href;return}wipe.classList.add("go");setTimeout(function(){location.href=a.href},360)});
if(matchMedia("(pointer:fine) and (min-width:1024px)").matches){var p=document.createElement("div");p.className="pointer";document.body.appendChild(p);addEventListener("pointermove",function(e){p.style.left=e.clientX+"px";p.style.top=e.clientY+"px";var hot=e.target.closest("a,button");p.classList.toggle("hot",!!hot)},{passive:true})}
})();
